#pragma once
#include <cstdlib>
#include "../Memory/Memory.h"

class OpcodeProcessor {
private:
	int screenWidth;
	int screenHeight;

public:

	OpcodeProcessor(int screenW = 64, int screenH = 32);
	~OpcodeProcessor() = default;

	void clearFrame(
		uint8_t* framebuffer, 
		bool* drawflag,
		uint16_t* pc);
	void returnFromSubroutine(
		uint16_t* pc, 
		uint16_t* stack,
		unsigned int* sp);
	void jumpToAdress(uint16_t opcode, uint16_t* pc);
	void callSubroutine(
		uint16_t opcode,
		uint16_t* pc,
		uint16_t* stack,
		unsigned int* sp);
	void skipNext1(
		uint16_t opcode,
		uint8_t* V,
		uint16_t* pc);
	void skipNext2(
		uint16_t opcode,
		uint8_t* V,
		uint16_t* pc);
	void skipNext3(
		uint16_t opcode,
		uint8_t* V,
		uint16_t* pc);
	void setVxToVn(
		uint16_t opcode,
		uint8_t* V,
		uint16_t* pc);
	void addVxToVn(
		uint16_t opcode,
		uint8_t* V,
		uint16_t* pc);
	void addNnToVx(
		uint16_t opcode,
		uint8_t* V,
		uint16_t* pc);
	void vx8FFF(
		uint16_t opcode,
		uint8_t* V,
		uint16_t* pc);
	void op9FFF(
		uint16_t opcode,
		uint8_t* V,
		uint16_t* pc);
	void opAFFF(
		uint16_t opcode,
		uint16_t* I,
		uint16_t* pc);
	void opBFFF(
		uint16_t opcode,
		uint16_t* pc,
		uint8_t* V);
	void opCFFF(
		uint16_t opcode,
		uint16_t* pc,
		uint8_t* V);
	void opEFFF(
		uint16_t opcode,
		uint16_t* pc,
		uint8_t* V,
		uint8_t* key);
	void beeping();
	void tickTimers(
		uint8_t* delay_timer,
		uint8_t* sound_timer);
	void opFF18(
		uint16_t opcode,
		uint8_t* sound_timer,
		uint16_t* pc,
		uint8_t* V);
	void opFF15(
		uint16_t opcode,
		uint8_t* delay_timer,
		uint16_t* pc,
		uint8_t* V);
	void opFF07(
		uint16_t opcode,
		uint8_t* delay_timer,
		uint16_t* pc,
		uint8_t* V);
	void setKey(
		int index, 
		bool pressed, 
		uint16_t* pc, 
		uint8_t* key, 
		uint8_t* V, 
		bool* waitingKey,
		uint8_t* awaitingRegister);
	void opFF0A(
		uint16_t opcode,
		bool* waitingKey,
		uint8_t* awaitingRegister);
	void opFF1E(
		uint16_t opcode,
		uint16_t* pc,
		uint8_t* V,
		uint16_t* I);
	void opFF29(
		uint16_t opcode,
		uint16_t* pc,
		uint8_t* V,
		uint16_t* I);
	void opFF33(
		uint16_t opcode, 
		uint16_t* pc,
		Memory* mem,
		uint16_t* I,
		uint8_t* V);
	void opD000(
		uint16_t opcode,
		uint8_t* framebuffer,
		uint8_t* V,
		uint16_t* I, 
		Memory* mem,
		bool* drawflag,
		uint16_t* pc);
	void detectPixelToDraw(
		uint8_t x, 
		int bit, 
		uint8_t y, 
		int row, 
		uint8_t spriteByte, 
		uint8_t* framebuffer, 
		uint8_t* V);
	/*uint8_t detectCollision(
		uint8_t x, 
		uint8_t y, 
		uint8_t* framebuffer);*/
	void opFF55(
		uint16_t opcode, 
		uint16_t* pc,
		Memory* mem,
		uint8_t* V,
		uint16_t* I);
	void opFF65(
		uint16_t opcode,
		uint16_t* pc,
		Memory* mem,
		uint8_t* V,
		uint16_t* I);
};